
name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout myproject
        uses: actions/checkout@v4

      - name: Verify firtool
        run: firtool --version

      - name: Compile
        run: |
          cd /home/shauryaps/playground
          make compile

      - name: Check
        run: |
          cd /home/shauryaps/myproject
          make check

      - name: Generate RTL
        run: |
          cd /home/shauryaps/myproject
          make rtl

